name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: apache/tomcat
        ref: master
        path: ./tomcat
    - run: ls "${GITHUB_WORKSPACE}/tomcat"
