name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repository: apache/tomcat
        ref: master
        path: ./tomcat
    - run: ls /home/runner/work/03_03-Passing-arguments-to-an-action/tomcat
