name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out Apache Tomcat
      uses: actions/checkout@v2
      with:
        repository: apache/tomcat
        ref: master
        path: ./tomcat

    - name: Copy tomcat-users.xml
      run: cp tomcat-users.xml ${GITHUB_WORKSPACE}/tomcat/conf/tomcat-users.xml
      
    - name: Compile Tomcat
      run: |
        cd ${GITHUB_WORKSPACE}/tomcat
        ant
